# Generated by Django 5.2.8 on 2025-11-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_extra_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
