# Generated by Django 5.2 on 2025-11-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_category_parent_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsection',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Товарная группа', 'verbose_name_plural': 'Товарные группы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.subsection', verbose_name='Товарная группа'),
        ),
    ]
