# Generated by Django 5.2 on 2025-11-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subsection',
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.section', verbose_name='Раздел'),
        ),
    ]
